### PR TITLE
add chinese version for 1.1

### PR DESCRIPTION
**Pull request by wanghaisheng**
pls check

### CODE REVIEW

**Comment by kba** [comment]
Great, thanks for your effort @wanghaisheng and @littlePP24.

I've made some minor adaptions to harmonize with the current state of the english translation and linked them from the README. I hope it's okay for you to equal country flag and language. If not, we can use text.

If you are interested in porting your changes to the current spec format, [drop us a line in gitter](https://gitter.im/kba/hocr-spec). I do not think it would be much effort (mostly copy/replace) and you'd get a [nice, accessible spec](http://kba.github.io/hocr-spec/1.2/) for the chinese-speaking developers, too.

**Comment by wanghaisheng** [comment]
sure,do you mean work according to files under https://github.com/kba/hocr-spec/tree/master/1.2 
i do have a question ,what is the relationship between spec.md and index.bs ,index.html 
are index.html transformed by the other 3?

**Comment by kba** [comment]
spec.md contains the text of the spec, nothing else. If you want to add your translation, adapt this file and send a PR and I will think about how we organize the files and build setup, so the chinese translation could be at http://kba.github.io/hocr-spec/1.2/zh/ or http://kba.github.io/hocr-spec/1.2-zh/

`metadata` contains the metadata [as understood by bikeshed](https://github.com/tabatkins/bikeshed/blob/master/docs/metadata.md).

We're using a [Makefile](https://github.com/kba/hocr-spec/blob/master/Makefile) that creates an HTML from the metadata, the [biblio.json](https://github.com/kba/hocr-spec/blob/master/biblio.json) (containing references to other specs) and the text of the spec which is fed into bikeshed and creates the spec website.

This should be properly documented :-)

**Comment by amitdo** [comment]
> This should be properly documented :-) 

:+1:

**Comment by kba** [comment]
@wanghaisheng I prepared a skeleton chinese version in the [1.2-zh](https://github.com/kba/hocr-spec/tree/zh-1.2) branch and made you a collaborator. You can add your changes directly to that branch, build instructions are in the README now. If you have any questions, ask away here or in gitter.

**Comment by wanghaisheng** [comment]
that`s nice @kba

**Pull request merged**
